import fs from "fs";
import { Report } from "../types.js";
import { META } from "../meta.js";

export function generateAgentFixPrompt(report: Report, outputPath: string) {
  let content = `# ${META.name} Fix Prompt
**Target:** ${report.finalUrl}
**Score:** ${report.score}/100 (${report.grade})

> You are an expert web developer. Please fix the following issues found by ${META.name}.

## Top Fixes Required

`;

  if (report.topFixes.length === 0) {
    content += "No major fixes required! Great job.\n";
  } else {
    report.topFixes.forEach((f, i) => {
      content += `### ${i + 1}. [${f.id}] ${f.message}\n`;
      content += `**How to fix:** ${f.fix}\n\n`;
    });
  }

  content += `\n---\n*Generated by ${META.name} v${META.version}*`;
  fs.writeFileSync(outputPath, content, "utf-8");
}
